#! /usr/bin/fish

set -l watch_path ( echo  $argv[1] | string split ' ' )
set -l run_cmd $argv[2..]

for file in $watch_path
    test -z $file; and continue

    if ! test -d $file; and ! test -f $file
        printf "\e[38;5;1mfile '%s' does not exist\n\e[m" $file >&2
        exit 1
    end
    printf "Watching %s\n" $file >&2
end

function clear
    printf "\e[1;1H\e[J"
end

command $run_cmd

while true

    inotifywait --exclude '^.git$' \
        -e modify \
        -r $watch_path &>/dev/null

    if ! test $status -eq 0
        printf "\e[38;1;mFailed to WatchFiles\e[m\n" >&2
        exit
    end

    clear

    command $run_cmd

    set -l cmd_status $status
    if ! string match -q $cmd_status 0
        set_color red
        printf "Failed: with status $cmd_status\n" >&2
        set_color normal
    end
end
